# Generated by Django 4.2 on 2023-04-15 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, null=True)),
                ('rating', models.CharField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], max_length=6, null=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(1799), django.core.validators.MaxLengthValidator(2030)])),
            ],
        ),
    ]
